### ISSUE TITLE
Typography should be brought over from the 1.7.0  to USWDS

### ISSUE THREAD

**Issue by alexiscott** [GetDKAN/data-catalog-app#60]
**Describe the bug**
As has been done with colors, we should ensure that we have Typography variables working at a general level with USWDS. Font sizes, and font families at a minimum.

@dgading 
Do you have any preferences in terms of how we handle font sizing? I saw some code in the general.scss file for this. I can just reuse that if we are happy with how that has been working.

Related links
https://designsystem.digital.gov/design-tokens/typesetting/overview/

**QA**
Expect to see some USWDS defaults:
  - the styles should have some declarative variables set, even if they are just reflecting defaults. I have added those to variables.scss.
 - Differences in sizes between H1 and H3 fonts. H1 being the largest.
 - Differences in font family between the body font and header fonts. Sans-serif vs serif respectively.
 - Body links underlined by default. 
 -  Also, one of the component styles coming through, as the import line is commented out.

**Comment by alexiscott** [comment]
I made a few changes so colors would go in their own file, meaning we don't need to use the legacy general scss file any more.

**Comment by cmugisha** [comment]
Action item for @alexiscott: check if a ticket to include new changes in the upgrade to 1.8.0 has already been created or not.

**Comment by dafeder** [comment]
Closing for now, this was just a stopgap that's no longer needed.
