### ISSUE TITLE
Spike: Edit link for logged in user on dataset page

### ISSUE THREAD

**Issue by dafeder** [GetDKAN/data-catalog-app#65]
## Background
On DKAN1, users were accustomed to going to a dataset page and seeing an edit button they could use make changes. Currently, to edit a dataset, users need to go to a manage content page in order to find and edit link to datasets. In user tests testing, this was found to be confusing for users who were accustomed to DKAN1. 

## User story
As a data publisher, when I am looking at a dataset page, I would like to be able to choose to edit it from that page, so that I don't need to leave the page to make changes. 

## Notes
If a user is logged in and has an active session, it would be a big UX improvement to see an edit link of some kind on a dataset.

To investigate: Is there an existing drop-in solution for decoupled Drupal sites to check for an authenticated user and provide contextual links?

Possible starting places:

* https://www.drupal.org/project/decoupled_kit
* https://www.drupal.org/project/decoupled_menus
* Ask front-end practice area

It may be that just turning on jsonAPI will give us all the endpoints we need and this is a question of writing a small request function and component on the dataset page.

## Acceptance criteria
- New ticket describing preferred approach and implementation plan

## Estimate: 5

**Comment by cmugisha** [comment]
Hi @dgading Could you please review this ticket or let me know when you're planning on reviewing it? Thanks!

**Comment by dgading** [comment]
I'm fine with whatever approach works best to get the logged status from Drupal. 

The big issues I would like to see addressed in implementation is creating a React context provider that has a function we can use to check for logged in status. The context would need to be wrapped around the entire app and then we could request it in any component that needs to know the current logged in status. It should probably recheck also whenever a new page asks for the information to catch possible logouts and stuff. I don't see that in this ticket, but could be added to the implementation ticket.

**Comment by cmugisha** [comment]
A new ticket (#74) came out of this. So closing this one.

**Comment by alexiscott** [comment]
> I'm fine with whatever approach works best to get the logged status from Drupal.
> 
> The big issues I would like to see addressed in implementation is creating a React context provider that has a function we can use to check for logged in status. The context would need to be wrapped around the entire app and then we could request it in any component that needs to know the current logged in status. It should probably recheck also whenever a new page asks for the information to catch possible logouts and stuff. I don't see that in this ticket, but could be added to the implementation ticket.

Working on the implementation for this in #74
